fixed bugs: 3055309 3055310 can't compile with mingw
git-svn-id: https://svn.code.sf.net/p/beye/code@15 00b2a026-ce94-4c24-9b4a-1a7d770b3cf8

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -161,7 +161,7 @@ fi
 
 srcdir=`pwd`
 #checking for pkg-config
-test $($pkg_config --version 2>/dev/null) || die "no pkg-config found"
+test $($pkg_config --version 2>/dev/null) || echo "no pkg-config found"
 #############################################################################
 test_optimizations config.mak config.h
 
@@ -224,6 +224,7 @@ case $cc_version in
     ;;
 esac
 # Printout architecture
+system=`echo $lc_host_os | tr [:upper:] [:lower:]`
 machine=generic
 if x86_32 ; then
 machine=ia32
@@ -252,11 +253,13 @@ app_cflags=""
 app_ldflags=""
 ar="ar -r"
 enable terminal_out
+exesuf=
 libext=a
 libprefix=lib
 if dos ; then
 app_ldflags="--force-exe-suffix"
 libext=lib
+exesuf=".exe"
 disable terminal_out
 fi
 if os2 ; then
@@ -266,12 +269,14 @@ disable terminal_out
 ar="emxomfar -p32 rc"
 ranlib=echo
 libext=lib
+exesuf=".exe"
 fi
 if win32 ; then
 app_libs="-lwinmm"
 app_ldflags="-mno-cygwin --force-exe-suffix"
 app_cflags="-mno-cygwin"
 libext=lib
+exesuf=".exe"
 disable terminal_out
 fi
 if beos ; then
@@ -303,6 +308,19 @@ print_config HAVE_ config.h config.mak pclose
 check_header sys/resource.h
 print_config HAVE_ config.h config.mak sys_resource_h
 
+check_header endian.h
+print_config HAVE_ config.h config.mak endian_h
+
+if disabled endian_h; then
+disable bigendian
+check_cc <<EOF || die "endian test failed"
+unsigned int endian = 'B' << 24 | 'I' << 16 | 'G' << 8 | 'E';
+EOF
+od -A n -t x1 $TMPO | grep -q '42 *49 *47 *45' && enable bigendian
+enabled bigendian && byteorder="__BIG_ENDIAN" || byteorder="__LITTLE_ENDIAN"
+fi
+
+
 if enabled iconv; then
 require2 giconv giconv.h iconv_open -lgiconv
 print_config HAVE_ config.h config.mak giconv
@@ -324,6 +342,11 @@ print_config HAVE_ config.h config.mak mouse
 echo "Creating config.h"
 cat >> config.h << EOF
 #define HOST "$host"
+
+#ifndef HAVE_ENDIAN_H
+#define __BYTE_ORDER $byteorder
+#endif
+
 /* Defined to some form of __attribute__ ((...)) if the compiler supports
    a different, more efficient calling convention.  */
 #if defined ( USE_FASTCALL ) && defined ( __i386__ )
@@ -348,6 +371,7 @@ CD=$cd
 CP=$cp
 INSTALL=$install
 PROGNAME=$prog_alias
+EXESUF=$exesuf
 LIBEXT=$libext
 LIBPREFIX=$libprefix
 PREFIX=$prefix
@@ -355,7 +379,7 @@ DATADIR=$datadir
 LIBDIR=$libdir
 MANDIR=$mandir
 DESTDIR=$DESTDIR
-HOST=$host_os
+HOST=$system
 MACHINE=$machine
 EOF
 echo "HOST_CFLAGS=$CFLAGS" >>config.mak
@@ -377,7 +401,7 @@ Config files successfully generated by ./configure !
   Ranlib: $ranlib
   Remover: $rm
   TARGETS
-    system: $host_os
+    system: $system
     arch: $machine
 
 EOF
